# Generated by Django 5.1.3 on 2024-11-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_city_event_country_event_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.TextField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(default='', max_length=150),
        ),
    ]
