from events.models import Event, SportType

def run():
    # Убедимся, что спорттипы существуют или создаем их
    sport_types = {
        "Дзюдо": SportType.objects.get_or_create(name="Дзюдо")[0],
        "Пауэрлифтинг": SportType.objects.get_or_create(name="Пауэрлифтинг")[0],
        "Самбо": SportType.objects.get_or_create(name="Самбо")[0],
        "Бокс": SportType.objects.get_or_create(name="Бокс")[0],
        "Тяжелая атлетика": SportType.objects.get_or_create(name="Тяжелая атлетика")[0],
    }

    events = [
        {
            "title": "ЧЕМПИОНАТ ЦЕНТРАЛЬНОГО ФЕДЕРАЛЬНОГО ОКРУГА",
            "sport_type": sport_types["Дзюдо"],
            "start_date": "2024-02-16",
            "end_date": "2024-02-19",
            "location": "МОСКОВСКАЯ ОБЛАСТЬ, г. Орехово-Зуево",
            "participants": 25,
            "gender": "mixed",
            "age_group": "от 14 лет и старше",
            "event_type": "Чемпионат",
            "description": "Основной состав",
            "program": "КЛАСС F-1D, дисциплина F-1D",
            "is_cancelled": False,
        },
        {
            "title": "ВСЕРОССИЙСКИЕ СОРЕВНОВАНИЯ",
            "sport_type": sport_types["Пауэрлифтинг"],
            "start_date": "2024-02-23",
            "end_date": "2024-02-25",
            "location": "РЕСПУБЛИКА БАШКОРТОСТАН, г. Уфа",
            "participants": 40,
            "gender": "male",
            "age_group": "от 18 лет и старше",
            "event_type": "Межрегиональные",
            "description": "Основной состав",
            "program": "ВЕСОВАЯ КАТЕГОРИЯ 98+ КГ, ВЕСОВАЯ КАТЕГОРИЯ 98 КГ, ВЕСОВАЯ КАТЕГОРИЯ 88 КГ",
            "is_cancelled": False,
        },
        {
            "title": "КУБОК РОССИИ",
            "sport_type": sport_types["Самбо"],
            "start_date": "2024-03-01",
            "end_date": "2024-03-03",
            "location": "ПЕНЗЕНСКАЯ ОБЛАСТЬ, г. Пенза",
            "participants": 30,
            "gender": "female",
            "age_group": "от 14 лет и старше",
            "event_type": "Кубок",
            "description": "Первый состав",
            "program": "КАТЕГОРИЯ ДО 60 КГ, КАТЕГОРИЯ ДО 70 КГ",
            "is_cancelled": False,
        },
        {
            "title": "ОКРУЖНЫЕ СОРЕВНОВАНИЯ",
            "sport_type": sport_types["Бокс"],
            "start_date": "2024-03-15",
            "end_date": "2024-03-17",
            "location": "НИЖЕГОРОДСКАЯ ОБЛАСТЬ, г. Нижний Новгород",
            "participants": 50,
            "gender": "male",
            "age_group": "от 16 лет и старше",
            "event_type": "Окружные",
            "description": "Сильнейшие бойцы",
            "program": "ЛЕГКАЯ ВЕСОВАЯ КАТЕГОРИЯ, СРЕДНЯЯ ВЕСОВАЯ КАТЕГОРИЯ, ТЯЖЕЛАЯ ВЕСОВАЯ КАТЕГОРИЯ",
            "is_cancelled": False,
        },
        {
            "title": "ЧЕМПИОНАТ РОССИИ ПО ТЯЖЕЛОЙ АТЛЕТИКЕ",
            "sport_type": sport_types["Тяжелая атлетика"],
            "start_date": "2024-04-01",
            "end_date": "2024-04-05",
            "location": "МОСКВА, г. Москва",
            "participants": 100,
            "gender": "mixed",
            "age_group": "от 18 лет и старше",
            "event_type": "Чемпионат",
            "description": "Лучшие атлеты страны",
            "program": "СОРЕВНОВАНИЯ ПО ТЯЖЕЛОМУ ЖИМУ, РЫВОК, ТОЛЧОК",
            "is_cancelled": False,
        },
        {
            "title": "КУБОК МИРА ПО САМБО",
            "sport_type": sport_types["Самбо"],
            "start_date": "2024-05-20",
            "end_date": "2024-05-25",
            "location": "СОЧИ, г. Сочи",
            "participants": 200,
            "gender": "mixed",
            "age_group": "от 18 лет и старше",
            "event_type": "Кубок",
            "description": "Международные соревнования",
            "program": "ТЕХНИЧЕСКАЯ ПРОГРАММА, ПОЕДИНКИ",
            "is_cancelled": False,
        },
        {
            "title": "ВСЕРОССИЙСКИЙ КУБОК ПО ДЗЮДО",
            "sport_type": sport_types["Дзюдо"],
            "start_date": "2024-06-01",
            "end_date": "2024-06-03",
            "location": "КРАСНОДАРСКИЙ КРАЙ, г. Краснодар",
            "participants": 80,
            "gender": "mixed",
            "age_group": "от 16 лет и старше",
            "event_type": "Кубок",
            "description": "Национальные соревнования",
            "program": "КАТЕГОРИЯ ДО 60 КГ, ДО 73 КГ, ДО 100 КГ, СВЫШЕ 100 КГ",
            "is_cancelled": False,
        },
    ]

    for event_data in events:
        Event.objects.create(**event_data)

    print("Тестовые данные добавлены.")
