# Generated by Django 5.1.3 on 2024-11-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(),
        ),
    ]
